//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cURL_Try1
{
    using System;
    using System.Collections.Generic;
    
    public partial class kortlinkDatabase
    {
        public int id { get; set; }
        public string kortlink { get; set; }
        public string redirectLocation { get; set; }
    }
}
